---
title: "Visuals"
author: "Mattia Lamberti"
date: "17/11/2022"
output: pdf_document
---

```{r setup, include=FALSE, cache = TRUE}
knitr::opts_chunk$set(include = FALSE)
```


```{r}
library(readr)
library(caret)
library(glmnet)
library(reshape) 
library(ROCit)
library(ggpubr)
library(cowplot)
library(grid)
library(gridExtra) 

setwd("C:/ARCHIVIO/2 - Magistrale/Semestre 3/Advanced statistical modelling fot Big Data/Progetto/Cells")
dat <- read_csv("dataset/dat_inverseStain.csv")


set.seed(200)
noise <- matrix(sample(0:10, 27558*1024, replace = T), nrow = 27558)
dat[,-1] <- dat[,-1] + noise

idx <- createDataPartition(dat$label, times=2, p=0.7)
train <- dat[idx$Resample1, ]
test <- dat[-idx$Resample1, ]

x <- model.matrix(label~., train)[,-1]
y <- train$label

```

```{r}
setwd("C:/ARCHIVIO/2 - Magistrale/Semestre 3/Advanced statistical modelling fot Big Data/Progetto/Cells")
load(file = 'CVobjects/cv_lasso_inverseStain.RData')

fit1 <- glmnet(x, y, family = "binomial", lambda =0)
fit_min <- glmnet(x, y, alpha = 1, family = "binomial", lambda = cv.lasso$lambda.min)
fit_1se <- glmnet(x, y, alpha = 1, family = "binomial", lambda = cv.lasso$lambda.1se)
```


```{r fig.height=2, fig.width=2}
mat_fit <- mat <- matrix((exp(coefficients(fit1)[-1])-1)*100, ncol=32, byrow = T)
data_melt_fit <- melt(mat_fit)

mat_fit_min <- mat <- matrix((exp(coefficients(fit_min)[-1])-1)*100, ncol=32, byrow = T)
data_melt_fit_min <- melt(mat_fit_min)

mat_fit_1se <- mat <- matrix((exp(coefficients(fit_1se)[-1])-1)*100, ncol=32, byrow = T)
data_melt_fit_1se <- melt(mat_fit_1se)

r <- range(c((exp(coefficients(fit1)[-1])-1)*100,
                 (exp(coefficients(fit1)[-1])-1)*100,
                 (exp(coefficients(fit1)[-1])-1)*100))


ggplot(data_melt_fit, aes(X1, X2)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient2(low = "blue",
                       mid = "gray95",
                       high = "red",
                       limits=r) +
  theme_void() + theme(legend.position = 'None')


ggplot(data_melt_fit_min, aes(X1, X2)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient2(low = "blue",
                       mid = "gray95",
                       high = "red",
                       limits=r) +
  theme_void() + theme(legend.position = 'None')


ggplot(data_melt_fit_1se, aes(X1, X2)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient2(low = "blue",
                       mid = "gray95",
                       high = "red",
                       limits=r) +
  theme_void() + theme(legend.position = 'None')
```


```{r fig.height=2, fig.width=1}
g <- ggplot(data_melt_fit, aes(X1, X2)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient2(low = "blue",
                       mid = "gray95",
                       high = "red",
                       limits=r, name = 'Value')

grid.newpage()
grid.draw(get_legend(g))
```

```{r  fig.height=2, fig.width=2}

# Original image
img<-matrix(as.numeric(test[6500,-1]), ncol=32, byrow=T)
data_melt <- melt(img)  
ggplot(data_melt, aes(X1, X2)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient2(low = "blue",
                       mid = "gray95",
                       high = "red",
                       limits=c(0,265))+
  theme_void()+
  theme(legend.position = "None")

mat <- matrix((exp(coefficients(fit_1se)[-1])-1)*100, ncol=32, byrow = T)
data_melt <- melt(mat)

# Coefficients
ggplot(data_melt, aes(X1, X2)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient2(low = "blue",
                       mid = "gray95",
                       high = "red") +
  theme_void() +
  theme(legend.position = "None")

# Product
intercept<- coef(fit_1se)[1]
coef <- matrix(coefficients(fit_1se)[-1], ncol=32, byrow = T)
p<-img*coef

data_melt <- melt(p)  
ggplot(data_melt, aes(X1, X2)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient2(low = "blue",
                       mid = "gray95",
                       high = "red")+
  theme_void()+
  theme(legend.position = "None")
```


```{r}
plot(cv.lasso)
```


```{r}
fitted_1se_prob <- as.numeric(predict(fit_1se, model.matrix(label~., test)[,-1], type='response'))

roc <- rocit(score=fitted_1se_prob, class=test$label)
plot(roc, YIndex=TRUE)
```

